#' Create plot of correlation magnitude from `correlation_test` object.
#'
#' This plot type is used in Brand et al. (2021). It presents the magnitudes
#' of the correlations from the real data as a solid red line, and the correlations
#' from each iteration of the permutation test as light blue lines. This gives
#' a visual sense of the distribution of random correlations compared with those
#' in the actual data.
#'
#' @param cor_test an object of class `correlation_test` generated by
#'   `correlation_test`.
#' @return `ggplot` object.
#' @importFrom dplyr bind_rows
#' @importFrom ggplot2 ggplot scale_alpha_manual scale_size_manual aes labs
#'   stat_density guides
#' @importFrom magrittr %>%
#' @importFrom glue glue
#' @examples
#' \dontrun{plot_correlation_magnitudes(cor_test)}
#' @export
plot_correlation_magnitudes <- function(cor_test) {

  cor_data <- bind_rows(
    "Permuted" = cor_test$permuted_correlations,
    "Original" = cor_test$original_correlations,
    .id = "Source"
  )

  cor_data %>%
    ggplot(
      aes(
        x = .data$cor,
        y = .data$..density..,
        colour = .data$Source,
        group = .data$iteration,
        alpha = .data$Source,
        size = .data$Source
      )
    ) +
    stat_density(geom = "line", position= "identity") +
    scale_alpha_manual(values = c("Permuted" = 0.2, "Original" = 1)) +
    scale_size_manual(values = c("Permuted" = 0.01, "Original" = 2)) +
    labs(
      title = glue(
        "Magnitude of Correlations in Original Data and {cor_test$iterations} Permutations"
      ),
      y = "Density",
      x = glue("Magnitude of correlation ({cor_test$cor_method})")
    ) +
    guides(alpha = "none", size = "none")

}

#' Create plot of correlation counts from `correlation_test` object.
#'
#' This plot presents the distribution of counts of significant correlations at
#' a given alpha level and the count of significant correlations in the
#' original data.
#'
#' @param cor_test an object of class `correlation_test` generated by
#'   `correlation_test`.
#' @param alpha significance level for counting correlation as significant.
#' @param jitter overlay jittered points representing count of significant
#'   pairwise correlations for each permutation.
#' @return `ggplot` object.
#' @importFrom dplyr bind_rows filter mutate summarise
#' @importFrom ggplot2 ggplot aes labs geom_violin geom_point geom_jitter
#' @importFrom magrittr %>%
#' @importFrom glue glue
#' @examples
#' \dontrun{plot_correlation_counts(cor_test)}
#' @export
plot_correlation_counts <- function(cor_test, alpha = 0.05, jitter = FALSE) {

  if (jitter) {
    jitter_element <- geom_jitter(alpha = 0.5)
  } else {
    jitter_element <- NULL
  }

  cor_test$permuted_correlations %>%
    filter(
      .data$cor_p <= alpha
    ) %>%
    group_by(.data$iteration) %>%
    summarise(
      n_sig = n()
    ) %>%
    mutate(
      source = "Null"
    ) %>%
    ggplot(
      aes(
        x = "",
        y = .data$n_sig,
        colour = .data$source
      )
    ) +
    geom_half_violin(
      alpha = 0.8,
      side = "r",
      draw_quantiles = c(0.25, 0.5, 0.75)
    ) +
    geom_half_point(
      size = 0.5,
      alpha = 0.8,
      side = "l"
    ) +
    jitter_element +
    geom_point(
      data = cor_test$original_correlations %>%
        filter(
          .data$cor_p <= alpha
        ) %>%
        summarise(
          n_sig = n()
        ) %>%
        mutate(
          source = "Data"
        )
    ) +
    labs(
      title = glue(
        "Count of Signficant Correlations in Original Data and ",
        "{cor_test$iterations} Permutations"
      ),
      y = "Count of significant correlations",
      x = "",
      caption = "Violin plot displays quartiles.",
      colour = "Source"
    )

}
