#' Create plot of variables by contribution to given PC.
#'
#' Plots match those given in supplementary material for Brand et al. (2021).
#' Variables are arranged by ascending contribution to the given PC, where
#' contribution is the squared loading for the variable expressed as a
#' percentage.
#'
#' @param pca_object a pca object generated by `prcomp` or `princomp`.
#' @param pc_no the PC to be visualised. Default value is 1.
#' @param cutoff the cutoff value for interpretation of the PC. Determines what
#'   total percentage contribution we want from the variables we select for
#'   interpretation. The default of 50 means that we pick the variables with the
#'   highest contribution to the PC until we have accounted for 50% of the total
#'   contributions to the PC.
#' @return `ggplot` object.
#' @export
#' @examples
#' pca_contrib_plot(pca_object, pc_no=1, cutoff=50)
#' pca_contrib_plot(pca_object, pc_no=2, cutoff=70)
pca_contrib_plot <- function(pca_object, pc_no=1, cutoff=50) {

  loadings <- as_tibble(onze_pca$rotation[,pc_no], rownames="variable") %>%
    rename(
      loading = value
    ) %>%
    mutate(
      contribution = (loading^2) * 100,
      loading_sign = if_else(loading < 0, "-", "+")
    ) %>%
    arrange(
      contribution
    ) %>%
    mutate(
      variable = fct_reorder(variable, contribution, min),
      cumulative_contribution = cumsum(contribution),
      highlight = cumulative_contribution > (100 - cutoff)
    )

  vertical_line_coord <- loadings %>%
    mutate(
      change_point = highlight != lead(highlight),
      row_no = 1,
      row_no = cumsum(row_no),
    ) %>%
    filter(
      change_point == TRUE
    ) %>%
    mutate(
      x_intercept = row_no + 0.5
    )

  loadings %>%
    ggplot(
      aes(
        x = variable,
        y = contribution,
        label = loading_sign,
        alpha = highlight,
        color = loading_sign
      )
    ) +
    geom_text(
      size = 6,
      fontface = "bold",
      show.legend = FALSE
    ) +
    geom_vline(
      aes(
        xintercept = x_intercept
      ),
      color = "red",
      linetype = "dashed",
      data = vertical_line_coord
    ) +
    scale_alpha_manual(
      values=c(0.4, 1)
    ) +
    scale_color_manual(
      values = c('red', 'black')
    ) +
    labs(
      title = paste0('PC', pc_no, ' Contribution Plot'),
      x = "Variable",
      y = "Contribution (%)"
    ) +
    theme(
      axis.text.x = element_text(angle = 90, hjust = 1, face = "bold"),
      axis.text.y = element_text(size = 14, face = "bold"),
      axis.title = element_text(size = 14, face = "bold")
    )
}
