#' Create plot of variables by contribution to given PC.
#'
#' Plots match those given in supplementary material for Brand et al. (2021).
#' Variables are arranged by ascending contribution to the given PC, where
#' contribution is the squared loading for the variable expressed as a
#' percentage.
#'
#' @param pca_object a pca object generated by `prcomp` or `princomp`.
#' @param pc_no the PC to be visualised. Default value is 1.
#' @param cutoff the cutoff value for interpretation of the PC. Determines what
#'   total percentage contribution we want from the variables we select for
#'   interpretation. The default of 50 means that we pick the variables with the
#'   highest contribution to the PC until we have accounted for 50% of the total
#'   contributions to the PC.
#' @return `ggplot` object.
#' @importFrom dplyr if_else lead rename mutate arrange filter
#' @importFrom forcats fct_reorder
#' @importFrom ggplot2 ggplot geom_text geom_vline scale_alpha_manual
#'     scale_color_manual aes labs theme element_text
#' @importFrom rlang .data
#' @importFrom tibble as_tibble
#' @importFrom magrittr %>%
#' @examples
#' \dontrun{pca_contrib_plot(pca_object, pc_no=1, cutoff=50)}
#' \dontrun{pca_contrib_plot(pca_object, pc_no=2, cutoff=70)}
#' @export
pca_contrib_plot <- function(pca_object, pc_no=1, cutoff=50) {

  loadings <- as_tibble(pca_object$rotation[,pc_no], rownames="variable") %>%
    rename(
      loading = .data$value
    ) %>%
    mutate(
      contribution = (.data$loading^2) * 100,
      loading_sign = if_else(.data$loading < 0, "-", "+")
    ) %>%
    arrange(
      .data$contribution
    ) %>%
    mutate(
      variable = fct_reorder(.data$variable, .data$contribution, base::min),
      cumulative_contribution = cumsum(.data$contribution),
      highlight = .data$cumulative_contribution > (100 - cutoff)
    )

  vertical_line_coord <- loadings %>%
    mutate(
      change_point = .data$highlight != lead(.data$highlight),
      row_no = 1,
      row_no = cumsum(.data$row_no),
    ) %>%
    filter(
      .data$change_point == TRUE
    ) %>%
    mutate(
      x_intercept = .data$row_no + 0.5
    )

  loadings %>%
    ggplot(
      aes(
        x = .data$variable,
        y = .data$contribution,
        label = .data$loading_sign,
        alpha = .data$highlight,
        color = .data$loading_sign
      )
    ) +
    geom_text(
      size = 6,
      fontface = "bold",
      show.legend = FALSE
    ) +
    geom_vline(
      aes(
        xintercept = .data$x_intercept
      ),
      color = "red",
      linetype = "dashed",
      data = vertical_line_coord
    ) +
    scale_alpha_manual(
      values=c(0.4, 1)
    ) +
    scale_color_manual(
      values = c('red', 'black')
    ) +
    labs(
      title = paste0('PC', pc_no, ' Contribution Plot'),
      x = "Variable",
      y = "Contribution (%)"
    ) +
    theme(
      axis.text.x = element_text(angle = 90, hjust = 1, face = "bold"),
      axis.text.y = element_text(size = 14, face = "bold"),
      axis.title = element_text(size = 14, face = "bold")
    )
}
