#' Simulate Mid-Point Vocalic Data
#'
#' Simulate F1 and F2 midpoint vocalic data for `n_speakers` speakers given a
#' collection of group means and standard deviations for any grouping structure
#' to be included in the simulation. Within-vowel covariation between F1 and F2
#' is automatically included. Any other patterns of covariation between
#' variables can be included by means of the `patterns` argument. The scale of
#' variation between speakers is controlled by the three standard deviation
#' arguments, which control variation due to induced covariation patterns,
#' random noise applied to each vowel category for each speaker, and how much
#' variance in vocal tract length there is, represented by a single scaling
#' parameter.
#'
#' @param grouped_means A tibble of grouped summary information about each vowel
#'   category and grouping variable. The tibble must be structured as follows:
#'
#' * `vowel`: character vector identifying vowel types.
#' * grouping variables: Optional character vectors identifying grouping
#'   structure required for simulation (such as gender or age categories)
#' * `mean_F1`: mean F1 value in Hz for group of speakers.
#' * `sd_F1`: sd of F1 values in Hz for group of speakers.
#' * `mean_F2`: mean F2 value in Hz for group of speakers.
#' * `sd_F2`: sd of F2 values in Hz for group of speakers.
#' * `cov_mat`: list column of (2x2) covariance matrices for within-vowel F1 and
#'    F2 covariation.
#'
#'  Appropriate matrices can be generated by [generate_grouped_means()].
#'
#' @param n_speakers Number of speakers to simulate. Default 1000.
#' @param probs List of probabilities passed to `sample()` to generate each
#'   grouping factor. If none given, then each level is given equal
#'   probabilities.
#' @param n_tokens_per_vowel Number of tokens to simulate per vowel. Default 30.
#'   If NULL, use mean token count for vowel category from actual data with
#'   `min_tokens_per_vowel` as control to ensure some tokens are present.
#' @param min_tokens_per_vowel Minimum tokens per vowel. Set to integer if
#'   `n_tokens_per_vowel` is `NULL` to ensure a minimum number of tokens for your
#'   analysis. Default NULL.
#' @param patterns List of pattern matrices (vowel x 2) representing covariation
#'   patterns. See documentation for [generate_orthogonal_pattern()] for the
#'   required structure.
#' @param pattern_sds Numeric vector of standard deviations for each pattern
#'   score.
#' @param speaker_noise_factor_sd SD of speaker-level noise factor. Default
#'   0.25.
#' @param scaling_factor_sd SD of speaker-level formant scaling factor. Default
#'   0.1.
#'
#' @return A tibble of simulated token-level formant data with speaker metadata.
#' @importFrom tibble tibble as_tibble
#' @importFrom dplyr mutate select filter group_by ungroup bind_cols pick any_of
#' @importFrom purrr map map2 pmap reduce2 set_names
#' @importFrom tidyr unnest
#' @examples
#' # Generate grouped means by gender from real corpus.
#' g_m <- generate_grouped_means(
#'  qb_vowels,
#'  grouping_variables = "participant_gender"
#' )
#' # Simulate 4 speakers, with 10 vowels per speaker and no between-vowel
#' # covariation
#' simulate_speakers(
#'   g_m,
#'   n_speakers = 4,
#'   n_tokens_per_vowel = 10
#' )
#' @export
simulate_speakers <- function(
  grouped_means,
  n_speakers = 1000,
  probs = NULL,
  n_tokens_per_vowel = 30,
  min_tokens_per_vowel = NULL,
  patterns = list(),
  pattern_sds = numeric(0),
  speaker_noise_factor_sd = 0.25,
  scaling_factor_sd = 0.1
) {

  stopifnot(length(patterns) == length(pattern_sds))

  # If `n_tokens_per_vowel` provided, replace existing `mean_tokens` column.
  if (!is.null(n_tokens_per_vowel)) {
    grouped_means[['mean_tokens']] <- n_tokens_per_vowel

  } else {
    stopifnot(
      "Must provide `min_tokens_per_vowel` if not providing `n_tokens_per_vowel`." =
        is.numeric(min_tokens_per_vowel)
    )
    grouped_means <- grouped_means |>
      mutate(
        mean_tokens = if_else(
          .data[['mean_tokens']] < min_tokens_per_vowel,
          min_tokens_per_vowel,
          .data[['mean_tokens']]
        )
      )
  }

  init_variables <- names(
    grouped_means[
     ,
      which(names(grouped_means) == "vowel"):which(names(grouped_means)=="mean_F1")
    ]
  )

  if (base::length(init_variables) > 2) {
    grouping_variables <- init_variables[
      2:
      (length(init_variables) - 1)
    ]
  } else {
    grouping_variables <- NULL
  }

  sim_speakers <- tibble(
    speaker = paste0("Speaker_", seq_len(n_speakers)),
  )

  for (i in seq_along(grouping_variables)) {
    sim_speakers <- sim_speakers |>
      mutate(
        !!grouping_variables[i] := sample(
          unique(grouped_means[[grouping_variables[i]]]),
          size = n_speakers,
          prob = probs[i],
          replace = TRUE
        )
      )
  }

  # Build named list of pattern score columns
  p_names <- paste0("p_", seq_along(patterns))

  # Add p columns dynamically
  p_cols <- map2(
    pattern_sds,
    p_names,
    \(sd, nm) {
      rnorm(n_speakers, mean = 0, sd = sd)
    }
  ) |>
  set_names(p_names) |>
  as_tibble()

  if (ncol(p_cols) > 0) {
    sim_dat <- sim_speakers |>
      bind_cols(p_cols)
  } else {
    sim_dat <- sim_speakers
  }

  sim_dat <- sim_dat |>
    mutate(
      # Two steps: first, get relevant means for grouping levels of
      # each speaker.
      speaker_means = pmap(
        as.list(
          pick(any_of(grouping_variables))
        ),
        \(...) {
          g_vals <- list(...)
          base_means <- filter_grouped_means(
            grouped_means, g_vals
          )
        }
      ),
      speaker_means = pmap(
        c(list(.data[['speaker_means']]), as.list(pick(any_of(p_names)))),
        \(speaker_means, ...) {
          p_vals <- list(...)
          reduce2(
            patterns,
            p_vals,
            \(means, pat, p) add_covar(means, mat2tbl(pat), speaker_factor = p),
            .init = speaker_means
           )
        }
      ),
      vocalic_data = map(
        .data[['speaker_means']],
        \(sm) {
          sm |>
            add_speaker_noise(factor_sd = speaker_noise_factor_sd) |>
            simulate_vs()
        }
      )
    ) |>
    select(-.data[['speaker_means']]) |>
    unnest(cols = .data[['vocalic_data']]) |>
    group_by(.data[['speaker']]) |>
    mutate(
      scaling_factor = rnorm(n = 1, mean = 1, sd = scaling_factor_sd)
    ) |>
    ungroup() |>
    mutate(
      sim_f1 = .data[['scaling_factor']] * .data[['sim_f1']],
      sim_f2 = .data[['scaling_factor']] * .data[['sim_f2']]
    )

  sim_dat
}


#' Generate an Orthogonal Covariation Pattern
#'
#' Generates a random vowel covariation pattern (F1/F2 shifts) that is
#' orthogonal to any existing patterns. Pattern matrices are n_vowels x 2
#' normalised matrices with a row for each vowel and a column for F1 and F2
#' shifts respectively. Sparse matrices can be generated which, for the first
#' pattern, will only have a defined number of non-zero loadings. Subsequent
#' patterns may have more non-zero loadings than the specified number, but
#' these should be small.
#'
#' @param vowels Character vector of vowel labels.
#' @param existing_patterns Optional list of existing pattern matrices to
#'   orthogonalise against.
#' @param sparse Optional integer. If supplied, retains only this many non-zero
#'   entries (by absolute value) before re-projecting onto the null space to
#'   ensure orthogonality.
#'
#' @return A normalized matrix of dimension \code{length(vowels) x 2} with
#'   dimnames \code{c("F1_shift", "F2_shift")}, or \code{NULL} if the space is
#'   fully spanned.
#' @importFrom stats rnorm
#' @examples
#' # Generate a pattern with only three non-zero loadings for
#' # given list of vowels.
#' vowels <- c("BED", "BATH", "BEYOND")
#' p_1 <- generate_orthogonal_pattern(vowels, sparse = 3)
#' # Generate another orthogonal to the first with four non-trivial
#' # entries.
#' p_1
#' p_2 <- generate_orthogonal_pattern(
#'   vowels,
#'   existing_patterns = list(p_1),
#'   sparse = 4
#' )
#' p_2
#' @export
generate_orthogonal_pattern <- function(vowels, existing_patterns = NULL, sparse = NULL) {

  n_vowels <- length(vowels)

  if (is.null(existing_patterns) || length(existing_patterns) == 0) {
    pattern_flat <- rnorm(n_vowels * 2)
    null_vectors <- NULL
  } else {
    existing_flat <- do.call(rbind, lapply(existing_patterns, function(p) as.vector(p)))

    svd_result <- svd(existing_flat, nu=0, nv=n_vowels*2)
    rank <- sum(svd_result$d > 1e-10)

    if (rank >= n_vowels * 2) {
      warning(
        "Space is fully spanned by existing patterns. No new pattern is possible."
      )
      return(NULL)
    }

    null_vectors <- svd_result$v[, (rank + 1):ncol(svd_result$v), drop = FALSE]
    coeffs <- rnorm(ncol(null_vectors))
    pattern_flat <- null_vectors %*% coeffs
  }

  if (!is.null(sparse)) {
    if (sparse >= n_vowels * 2) {
      warning("sparse >= total entries; ignoring sparsity constraint.")
    } else {
      # Zero out all but the top `sparse` entries by absolute value
      threshold_idx <- order(abs(pattern_flat), decreasing = TRUE)[-seq_len(sparse)]
      pattern_flat[threshold_idx] <- 0

      # Re-project onto null space to restore orthogonality
      if (!is.null(null_vectors)) {
        pattern_flat <- null_vectors %*% (t(null_vectors) %*% pattern_flat)
      }
    }
  }

  pattern <- matrix(
    pattern_flat,
    nrow = n_vowels,
    ncol = 2,
    dimnames = list(
      vowels,
      c("F1_shift", "F2_shift")
    )
  )
  pattern <- pattern / norm(pattern, type = "F")
  pattern
}

#' Convert a Pattern Tibble to a Matrix
#'
#' It is convenient to switch between tibble representations and
#' n x 2 matrix representations of covariation patterns. This
#' function does the convension from tibble to matrix.
#'
#' @param in_tbl A tibble with columns \code{vowel}, \code{F1_shift}, \code{F2_shift}.
#'
#' @return A numeric matrix with rownames set to vowel labels.
#' @importFrom dplyr select
#' @importFrom tibble as_tibble
#' @export
#' @examples
#' # Generate a pattern with only three non-zero loadings for
#' # given list of vowels.
#' vowels <- c("BED", "BATH", "BEYOND")
#' p_1 <- generate_orthogonal_pattern(vowels, sparse = 3)
#' # Generate another orthogonal to the first with four non-trivial
#' # entries.
#' tbl_pat <- mat2tbl(p_1)
#' tbl2mat(tbl_pat)
tbl2mat <- function(in_tbl) {
  vowels <- in_tbl$vowel
  out_mat <- in_tbl |>
    select(.data[['F1_shift']], .data[['F2_shift']]) |>
    as.matrix()
  rownames(out_mat) <- vowels
  out_mat
}


#' Convert a Vowel Pattern Matrix to a Tibble
#'
#' It is convenient to switch between tibble representations and
#' n x 2 matrix representations of covariation patterns. This
#' function does the convension from matric to tibble.
#'
#' @param in_mat A numeric matrix with rownames corresponding to vowel labels
#'   and columns \code{F1_shift} and \code{F2_shift}.
#'
#' @return A tibble with columns \code{vowel}, \code{F1_shift}, \code{F2_shift}.
#' @importFrom tibble as_tibble
#' @export
#' @examples
#' # Generate a pattern with only three non-zero loadings for
#' # given list of vowels.
#' vowels <- c("BED", "BATH", "BEYOND")
#' p_1 <- generate_orthogonal_pattern(vowels, sparse = 3)
#' # Generate another orthogonal to the first with four non-trivial
#' # entries.
#' mat2tbl(p_1)
mat2tbl <- function(in_mat) {
  out_tbl <- in_mat |>
    as_tibble(
      rownames = "vowel"
    )
  out_tbl
}

#' Generate Grouped Means for Vowel Formant Data
#'
#' Computes grouped means, standard deviations, correlations, and covariance
#' matrices for F1 and F2 vowel formant data, optionally stratified by
#' additional grouping variables.
#'
#' @param vowel_data A data frame where column 1 is a character/factor of
#'   speaker IDs, column 2 is a character/factor of vowel IDs, column 3 is
#'   numeric F1 values, and column 4 is numeric F2 values.
#' @param grouping_variables A character vector of additional column names in
#'   `vowel_data` to group by, or `NULL` (default) to group by vowel ID only.
#'
#' @return A grouped/summarised tibble containing:
#'   \item{mean_F1}{Mean F1 per group.}
#'   \item{sd_F1}{Standard deviation of F1 per group.}
#'   \item{mean_F2}{Mean F2 per group.}
#'   \item{sd_F2}{Standard deviation of F2 per group.}
#'   \item{cor_f1_f2}{Pearson correlation between F1 and F2 per group.}
#'   \item{cov_mat}{A list-column of 2x2 covariance matrices for F1 and F2.}
#'
#' @importFrom dplyr group_by across all_of summarise ungroup
#' @importFrom rlang .data
#' @importFrom stats sd cor
#'
#' @examples
#' generate_grouped_means(qb_vowels, grouping_variables = "participant_gender")
#'
#' @export
generate_grouped_means <- function(vowel_data, grouping_variables = NULL) {

  base::stopifnot(
    "Column one must be a factor or character vector of speaker ids." =
      base::is.character(vowel_data[[1]]) | base::is.factor(vowel_data[[1]]),
    "Column two must be a factor or character vector of vowel ids." =
      base::is.character(vowel_data[[2]]) | base::is.factor(vowel_data[[2]]),
    "Column three must be a numeric vector of F1 values." =
      base::is.numeric(vowel_data[[3]]),
    "Column four must be a numeric vector of F2 values." =
      base::is.numeric(vowel_data[[4]]),
    "Grouping column not found in data." =
      (
        base::is.null(grouping_variables) |
          all(grouping_variables %in% base::names(vowel_data))
      )
  )

  speaker_col_name <- base::names(vowel_data)[[1]]
  vowel_col_name <- base::names(vowel_data)[[2]]
  F1_col_name <- base::names(vowel_data)[[3]]
  F2_col_name <- base::names(vowel_data)[[4]]

  # Get average token counts for each speaker.
  vowel_data <- vowel_data |>
    group_by(.data[[speaker_col_name]], .data[[vowel_col_name]]) |>
    mutate(
      n_tokens = n()
    ) |>
    ungroup()

  if (is.null(grouping_variables)) {
    grouped_means <- vowel_data |>
      group_by(.data[[vowel_col_name]])
  } else {
    grouped_means <- vowel_data |>
      group_by(.data[[vowel_col_name]], across(all_of(grouping_variables)))
  }

  grouped_means <- grouped_means |>
    summarise(
      mean_F1 = mean(.data[[F1_col_name]]),
      sd_F1 = sd(.data[[F1_col_name]]),
      mean_F2 = mean(.data[[F2_col_name]]),
      sd_F2 = sd(.data[[F2_col_name]]),
      cor_f1_f2 = cor(.data[[F1_col_name]], .data[[F2_col_name]]),
      # Build covariance matrix and store as list-column
      cov_mat = list(
        matrix(
          c(
            .data[['sd_F1']]^2,
            .data[['cor_f1_f2']] * .data[['sd_F1']] * .data[['sd_F2']],
            .data[['cor_f1_f2']] * .data[['sd_F1']] * .data[['sd_F2']],
            .data[['sd_F2']]^2
          ),
          nrow = 2,
          dimnames = list(
            c(F1_col_name, F2_col_name),
            c(F1_col_name, F2_col_name)
          )
        )
      ),
      mean_tokens = base::round(base::mean(.data[['n_tokens']]))
    )
  grouped_means
}

#' Add Covariation Pattern to Speaker Means
#'
#' Shifts \code{mean_F1} and \code{mean_F2} in \code{speaker_means} according
#' to a covariation pattern, scaled by the speaker's standard deviations and an
#' optional speaker-level factor.
#'
#' @param speaker_means A tibble containing columns \code{vowel},
#'   \code{mean_F1}, \code{mean_F2}, \code{sd_F1}, and \code{sd_F2}.
#' @param shifts A tibble or matrix with columns \code{vowel}, \code{F1_shift},
#'   and \code{F2_shift} giving the pattern loadings per vowel. If a matrix,
#'   rownames are used as vowel labels.
#' @param speaker_factor Numeric scalar controlling the magnitude of the applied
#'   shift. This is always used in practice, as variation between speakers in
#'   terms of the extent to which they are affected by a pattern is necessary
#'   for any population level variation in line with the pattern. Default
#'   \code{1}.
#'
#' @return A tibble with updated \code{mean_F1} and \code{mean_F2} columns.
#'
#' @importFrom tibble is_tibble as_tibble
#' @importFrom dplyr left_join mutate select
#' @export
#' @examples
#' # Generate a pattern with only three non-zero loadings for
#' # given list of vowels.
#' vowels <- c("BED", "BATH", "BEYOND")
#' p_1 <- generate_orthogonal_pattern(vowels, sparse = 3)
#' speaker_means <- tibble::tibble(
#'   vowel = c("BED", "BATH", "BEYOND"),
#'   mean_F1 = c(500, 600, 700),
#'   sd_F1 = c(30, 20, 50),
#'   mean_F2 = c(1500, 1700, 1300),
#'   sd_F2 = c(70, 60, 90),
#' )
#' # Modify speaker means in accordance with `p_1`
#' add_covar(speaker_means, p_1)
add_covar <- function(speaker_means, shifts, speaker_factor = 1) {

  if (!is_tibble(shifts)) {
    shifts <- shifts |>
      as_tibble(rownames = "vowel")
  }

  speaker_means |>
    # ensure not grouped by vowel
    left_join(
      shifts,
      by = "vowel"
    ) |>
    mutate(
      mean_F1 = .data[["mean_F1"]] +
        .data[["F1_shift"]] * speaker_factor * .data[["sd_F1"]],
      mean_F2 = .data[['mean_F2']] +
        .data[['F2_shift']] * speaker_factor * .data[['sd_F2']],
    ) |>
    select(-.data[['F1_shift']], -.data[['F2_shift']])
}

#' Filter grouped means by specified values
#'
#' @param g_means A data frame of grouped means.
#' @param g_values A named list of column-value pairs to filter by.
#'
#' @return A data frame filtered to rows matching all values in \code{g_values},
#'   ungrouped and with the grouping columns removed.
#'
#' @importFrom purrr reduce2
#' @importFrom dplyr ungroup select any_of
filter_grouped_means <- function(g_means, g_values) {
  out_df <-
    reduce2(
      names(g_values),
      g_values,
      \(df, name, val) {df[df[[name]] == val, ]},
      .init = g_means
    ) |>
    ungroup() |>
    select(-any_of(names(g_values)))
}

#' Simulate vowel spaces from speaker means
#'
#' @param speaker_means A data frame containing columns \code{cov_mat},
#'   \code{mean_F1}, and \code{mean_F2}.
#' @return A data frame with columns \code{sim_f1} and \code{sim_f2} added,
#'   unnested to one row per simulated observation.
#' @importFrom purrr pmap
#' @importFrom dplyr mutate select
#' @importFrom tidyr unnest
#' @importFrom MASS mvrnorm
#' @importFrom tibble as_tibble
simulate_vs <- function(speaker_means) {
  speaker_means |>
    mutate(
      sim = pmap(
        list(
          .data[['cov_mat']], .data[['mean_F1']],
          .data[['mean_F2']], .data[['mean_tokens']]
        ),
        \(cm, f1, f2, n_samples) {
          mvrnorm(
            n = n_samples,
            mu = c(f1, f2),
            Sigma = cm
          ) |>
            as_tibble(.name_repair = ~c("sim_f1", "sim_f2"))
        }
 )
    ) |>
    select(-.data[['cov_mat']]) |>
    unnest(.data[['sim']])
}

#' Add random speaker-level noise to formant means
#'
#' Perturbs \code{mean_F1} and \code{mean_F2} by a normally distributed random
#' offset scaled by the respective standard deviations and \code{factor_sd}.
#'
#' @param speaker_means A data frame containing columns \code{mean_F1},
#'   \code{mean_F2}, \code{sd_F1}, and \code{sd_F2}.
#' @param factor_sd Numeric. Scaling factor for the noise standard deviation.
#'   Default \code{0.25}.
#'
#' @return A data frame with jittered \code{mean_F1} and \code{mean_F2} columns.
#'
#' @importFrom dplyr ungroup mutate
add_speaker_noise <- function(speaker_means, factor_sd = 0.25) {
  speaker_means |>
    # ensure not grouped by vowel
    ungroup() |>
    mutate(
      mean_F1 = .data[['mean_F1']] +
        rnorm(n = nrow(speaker_means), 0, factor_sd) * .data[['sd_F1']],
      mean_F2 = .data[['mean_F2']] +
        rnorm(n = nrow(speaker_means), 0, factor_sd) * .data[['sd_F2']]
    )
}
